# Generated by Django 4.0.3 on 2022-04-27 03:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timesheetapp', '0002_rename_account_number_employees_tabel_number'),
    ]

    operations = [
        migrations.CreateModel(
            name='Holidays',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.DateField()),
            ],
        ),
        migrations.RenameField(
            model_name='timework',
            old_name='all_hours',
            new_name='common_hours',
        ),
    ]
